"""
Settings
"""
import os  # isort:skip
from pathlib import Path
from decouple import config



def gettext(s):
    """
    Return the translated version of the input string 's'.

    This function is used for translation purposes.
    """
    return s


DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for ensam project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = '%dqf8l7n1!ja76drjg+3ac+=xrn$b@b6hb1^j0z7#_)i++l5n9'
SECRET_KEY = config('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition


ROOT_URLCONF = 'ensam.urls'

WSGI_APPLICATION = 'ensam.wsgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')


if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(DATA_DIR, 'static')


SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'ensam', 'templates'), ],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_googlemap',
    'djangocms_video',
    'ensam',
    'app'
]

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')), ('fr', gettext('fr')),

)

CMS_LANGUAGES = {
    ## Customize this
    1: [
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'fr',
            'name': gettext('fr'),
            'redirect_on_fallback': True,
            'public': True,
            'hide_untranslated': False,
        },
    ],
    'default': {
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}

CMS_TEMPLATES = (
    ## Customize this
    ('fullwidth.html', 'Fullwidth'),
    # ('sidebar_left.html', 'Sidebar Left'),
    # ('sidebar_right.html', 'Sidebar Right'),
    ('index.html', 'Home'),
    ('Titre.html', 'Vide'),
    ('contact.html', 'Contact'),
    ('Cooperation/nationnnale.html', 'Cooperation/nationnale'),
    ('Cooperation/internationnale.html', 'Cooperation/internationnale'),
    ('Ecole/presentation.html', 'Ecole/Presentation'),
    ('Ecole/mot_du_directeur.html', 'Ecole/mot_du_directeur'),
    ('Ecole/Actualites.html', 'Ecole/Actualities'),
    ('Ecole/corps_professoral.html', 'Ecole/Corps_professoral'),
    ('Ecole/recrutements.html', 'Ecole/Recrutements'),
    ('Ecole/reglement_interieur.html', 'Ecole/Reglement_Interieur'),
    ('Ecole/appel_offres.html', 'Ecole/appel_offres'),
    ('Etudiant/service_aux_etudiants.html', 'Etudiant/service_aux_etudiants'),
    ('Etudiant/e-doc.html', 'Etudiant/E-DOC'),
    ('Etudiant/clubs.html', 'Etudiant/clubs'),
    ('Etudiant/emplois_du_temps.html', 'Etudiant/emplois_du_temps'),
    ('Etudiant/avis_aux_etudiants.html', 'Etudiant/avis_aux_etudiants'),
    ('Etudiant/Ent.html', 'Etudiant/Ent'),
    ('Recherche/equipes_laboratoires.html', 'Recherche/equipe_laboiratoires'),
    ('Recherche/projet_ensam.html', 'Recherche/projet_ensam'),
    ('Recherche/formation-doctorale.html', 'Recherche/formation-doctorale'),
    ('Recherche/manifestations-scientifiques.html', 'Recherche/manifestations-scientifiques'),
    ('E-learning/base_de_donnees_scientifiques.html', 'E-learning/base-de-donnees-scientifiques'),
    ('Departement/departement-genie-industriel.html', 'Department/departement-genie-industriel'),
    ('Departement/departement.html', 'Department/departement'),
    ('Departement/departement-genie-mecanique.html', 'Department/departement-genie-mecanique'),
    ('Departement/departement-genie-electrique.html', 'Department/departement-genie-electrique'),
    ('Departement/departement-genie-electrique.html', 'Department/departement-genie-electrique'),
    ('Formation/formation.html', 'Formation'),
    ('Formation/formation-continue.html', 'Formation/formation-continue'),
    ('Formation/master.html', 'Formation/master'),
    ('Formation/cycle-preparatoire.html', 'Formation/prepa'),
    ('Formation/cycle-inginieur.html', 'Formation/ingineur'),
    ('laureats/laureats.html', 'laureats/laureats'),
    ('laureats/ceremonie.html', 'laureats/ceremonie'),
    ('gallery.html', 'Gallery'),

)
CMS_CONFIRM_VERSION4 = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default': {
        'CONN_HEALTH_CHECKS': 'False',
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ensam',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',  # ou l'adresse IP de votre serveur MySQL
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
